#pragma once
#include "Graphics/color_options.h"

// ==== CONFIG ====================================================

// convert vgaboard-style #defines
#ifndef VIDEO_COLOR_PIN_BASE

  #ifdef PICO_SCANVIDEO_ENABLE_CLOCK_PIN
	#define VIDEO_ENABLE_CLOCK_PINS PICO_SCANVIDEO_ENABLE_CLOCK_PIN
  #endif
  #ifdef PICO_SCANVIDEO_CLOCK_POLARITY
	#define VIDEO_CLOCK_POLARITY PICO_SCANVIDEO_CLOCK_POLARITY
  #endif
  #ifdef PICO_SCANVIDEO_DEN_POLARITY
	#define VIDEO_DEN_POLARITY PICO_SCANVIDEO_DEN_POLARITY
  #endif

  #define VIDEO_COLOR_PIN_BASE PICO_SCANVIDEO_COLOR_PIN_BASE
  #define VIDEO_SYNC_PIN_BASE  PICO_SCANVIDEO_SYNC_PIN_BASE
//#define VIDEO_CLOCK_ENABLE   PICO_SCANVIDEO_ENABLE_CLOCK_PIN
//#define VIDEO_CLOCK_POLARITY PICO_SCANVIDEO_CLOCK_POLARITY
//#define VIDEO_DEN_ENABLE	   PICO_SCANVIDEO_ENABLE_DEN_PIN
//#define VIDEO_DEN_POLARITY   PICO_SCANVIDEO_DEN_POLARITY
#endif

#ifndef VIDEO_CLOCK_ENABLE
  #undef VIDEO_DEN_ENABLE
  #define VIDEO_CLOCK_ENABLE false
#endif
#ifndef VIDEO_DEN_ENABLE
  #define VIDEO_DEN_ENABLE false
#endif
#ifndef VIDEO_CLOCK_POLARITY
  #define VIDEO_CLOCK_POLARITY 0
#endif
#ifndef VIDEO_DEN_POLARITY
  #define VIDEO_DEN_POLARITY 0
#endif
#ifndef VIDEO_CLOCK_PIN_BASE
  #define VIDEO_CLOCK_PIN_BASE 0
#endif

#ifndef VIDEO_MAX_SYSCLOCK_MHz
  #define VIDEO_MAX_SYSCLOCK_MHz 290
#endif
