#pragma once


// ==== CONFIG ====================================================

// pull in board description file for targeted board:
#ifndef UNIT_TEST
  #include <pico/config.h>
#endif


// convert vgaboard-style #defines
#ifndef VIDEO_COLOR_PIN_BASE

  #ifndef PICO_SCANVIDEO_COLOR_PIN_COUNT
	#define PICO_SCANVIDEO_COLOR_PIN_COUNT 16
  #endif
  #ifndef PICO_SCANVIDEO_PIXEL_RSHIFT
	#define PICO_SCANVIDEO_PIXEL_RSHIFT 0u
  #endif
  #ifndef PICO_SCANVIDEO_PIXEL_GSHIFT
	#define PICO_SCANVIDEO_PIXEL_GSHIFT 6u
  #endif
  #ifndef PICO_SCANVIDEO_PIXEL_BSHIFT
	#define PICO_SCANVIDEO_PIXEL_BSHIFT 11u
  #endif
  #ifndef PICO_SCANVIDEO_PIXEL_RCOUNT
	#define PICO_SCANVIDEO_PIXEL_RCOUNT 5
  #endif
  #ifndef PICO_SCANVIDEO_PIXEL_GCOUNT
	#define PICO_SCANVIDEO_PIXEL_GCOUNT 5
  #endif
  #ifndef PICO_SCANVIDEO_PIXEL_BCOUNT
	#define PICO_SCANVIDEO_PIXEL_BCOUNT 5
  #endif

  #ifdef PICO_SCANVIDEO_ENABLE_CLOCK_PIN
	#define VIDEO_ENABLE_CLOCK_PINS PICO_SCANVIDEO_ENABLE_CLOCK_PIN
  #endif
  #ifdef PICO_SCANVIDEO_CLOCK_POLARITY
	#define VIDEO_CLOCK_POLARITY PICO_SCANVIDEO_CLOCK_POLARITY
  #endif
  #ifdef PICO_SCANVIDEO_DEN_POLARITY
	#define VIDEO_DEN_POLARITY PICO_SCANVIDEO_DEN_POLARITY
  #endif

  #define VIDEO_COLOR_PIN_BASE PICO_SCANVIDEO_COLOR_PIN_BASE
  #define VIDEO_SYNC_PIN_BASE  PICO_SCANVIDEO_SYNC_PIN_BASE
//#define VIDEO_CLOCK_ENABLE   PICO_SCANVIDEO_ENABLE_CLOCK_PIN
//#define VIDEO_CLOCK_POLARITY PICO_SCANVIDEO_CLOCK_POLARITY
//#define VIDEO_DEN_ENABLE	   PICO_SCANVIDEO_ENABLE_DEN_PIN
//#define VIDEO_DEN_POLARITY   PICO_SCANVIDEO_DEN_POLARITY

  #define VIDEO_COLOR_PIN_COUNT PICO_SCANVIDEO_COLOR_PIN_COUNT
  #define VIDEO_PIXEL_RSHIFT	PICO_SCANVIDEO_PIXEL_RSHIFT
  #define VIDEO_PIXEL_GSHIFT	PICO_SCANVIDEO_PIXEL_GSHIFT
  #define VIDEO_PIXEL_BSHIFT	PICO_SCANVIDEO_PIXEL_BSHIFT
  #define VIDEO_PIXEL_RCOUNT	PICO_SCANVIDEO_PIXEL_RCOUNT
  #define VIDEO_PIXEL_GCOUNT	PICO_SCANVIDEO_PIXEL_GCOUNT
  #define VIDEO_PIXEL_BCOUNT	PICO_SCANVIDEO_PIXEL_BCOUNT
#endif

#ifndef VIDEO_CLOCK_ENABLE
  #undef VIDEO_DEN_ENABLE
  #define VIDEO_CLOCK_ENABLE false
#endif
#ifndef VIDEO_DEN_ENABLE
  #define VIDEO_DEN_ENABLE false
#endif
#ifndef VIDEO_CLOCK_POLARITY
  #define VIDEO_CLOCK_POLARITY 0
#endif
#ifndef VIDEO_DEN_POLARITY
  #define VIDEO_DEN_POLARITY 0
#endif
#ifndef VIDEO_CLOCK_PIN_BASE
  #define VIDEO_CLOCK_PIN_BASE 0
#endif

#ifndef VIDEO_MAX_SYSCLOCK_MHz
  #define VIDEO_MAX_SYSCLOCK_MHz 290
#endif


// check minimal plausibility:
static_assert(VIDEO_PIXEL_RSHIFT + VIDEO_PIXEL_RCOUNT <= VIDEO_COLOR_PIN_COUNT);
static_assert(VIDEO_PIXEL_GSHIFT + VIDEO_PIXEL_GCOUNT <= VIDEO_COLOR_PIN_COUNT);
static_assert(VIDEO_PIXEL_BSHIFT + VIDEO_PIXEL_BCOUNT <= VIDEO_COLOR_PIN_COUNT);
